### ISSUE TITLE
I'd love to contribute to the frontend 

### ISSUE THREAD

**Issue by JaeKralj** [osinkolu/Agrobotfarms#6]
I'd like to fix some bugs in the header and overall page layout for mobile screens.

I'd love to know how I can contribute

**Comment by osinkolu** [comment]
Hi @JaeKralj, there's no official way of contributing yet on the repo, or strict guidelines. Please feel free to fork the repository, and send a pull request with detailed comments on the changes you made. Thanks.

Please note, I'll close this issue, as this is not a real issue.

**Comment by JaeKralj** [comment]
Noted
